oneup_flysystem:
    adapters:
        assets_adapter:
            awss3v3:
                client: app.assets.s3
                bucket: 'env(%assets_bucket)%'
                prefix: assets

    filesystems:
        assets_fs:
            adapter:    assets_adapter
            mount:      assets_fs

